/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anime-grid/': RouteRecordInfo<
      '/anime-grid/',
      '/anime-grid',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/anxiary/': RouteRecordInfo<
      '/anxiary/',
      '/anxiary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/paper/Eyeriss': RouteRecordInfo<
      '/paper/Eyeriss',
      '/paper/Eyeriss',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/paper/StringingSpills': RouteRecordInfo<
      '/paper/StringingSpills',
      '/paper/StringingSpills',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/11.11-Simulation-Contest-Summary': RouteRecordInfo<
      '/posts/11.11-Simulation-Contest-Summary',
      '/posts/11/11-Simulation-Contest-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/11.12-Simulation-Contest-Summary': RouteRecordInfo<
      '/posts/11.12-Simulation-Contest-Summary',
      '/posts/11/12-Simulation-Contest-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/11.13-Simulation-Contest-Summary': RouteRecordInfo<
      '/posts/11.13-Simulation-Contest-Summary',
      '/posts/11/13-Simulation-Contest-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/11.9-Simulation-Contest-Summary': RouteRecordInfo<
      '/posts/11.9-Simulation-Contest-Summary',
      '/posts/11/9-Simulation-Contest-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/aboutme': RouteRecordInfo<
      '/posts/aboutme',
      '/posts/aboutme',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/anime2023': RouteRecordInfo<
      '/posts/anime2023',
      '/posts/anime2023',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Another-Request': RouteRecordInfo<
      '/posts/Another-Request',
      '/posts/Another-Request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/apple-tree-2': RouteRecordInfo<
      '/posts/apple-tree-2',
      '/posts/apple-tree-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CCF-Arch-Fault-Injection-Survey-2021-2025': RouteRecordInfo<
      '/posts/CCF-Arch-Fault-Injection-Survey-2021-2025',
      '/posts/CCF-Arch-Fault-Injection-Survey-2021-2025',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/College-Literature': RouteRecordInfo<
      '/posts/College-Literature',
      '/posts/College-Literature',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Common-Mistakes': RouteRecordInfo<
      '/posts/Common-Mistakes',
      '/posts/Common-Mistakes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_1': RouteRecordInfo<
      '/posts/CourseOfDCS_1',
      '/posts/CourseOfDCS_1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_10': RouteRecordInfo<
      '/posts/CourseOfDCS_10',
      '/posts/CourseOfDCS_10',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_2': RouteRecordInfo<
      '/posts/CourseOfDCS_2',
      '/posts/CourseOfDCS_2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_3': RouteRecordInfo<
      '/posts/CourseOfDCS_3',
      '/posts/CourseOfDCS_3',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_4': RouteRecordInfo<
      '/posts/CourseOfDCS_4',
      '/posts/CourseOfDCS_4',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_5': RouteRecordInfo<
      '/posts/CourseOfDCS_5',
      '/posts/CourseOfDCS_5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_6': RouteRecordInfo<
      '/posts/CourseOfDCS_6',
      '/posts/CourseOfDCS_6',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_7': RouteRecordInfo<
      '/posts/CourseOfDCS_7',
      '/posts/CourseOfDCS_7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_8': RouteRecordInfo<
      '/posts/CourseOfDCS_8',
      '/posts/CourseOfDCS_8',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_9': RouteRecordInfo<
      '/posts/CourseOfDCS_9',
      '/posts/CourseOfDCS_9',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfDCS_highlight': RouteRecordInfo<
      '/posts/CourseOfDCS_highlight',
      '/posts/CourseOfDCS_highlight',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfFaultTorrence': RouteRecordInfo<
      '/posts/CourseOfFaultTorrence',
      '/posts/CourseOfFaultTorrence',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CourseOfISP': RouteRecordInfo<
      '/posts/CourseOfISP',
      '/posts/CourseOfISP',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/DiaryOfKeyan240827': RouteRecordInfo<
      '/posts/DiaryOfKeyan240827',
      '/posts/DiaryOfKeyan240827',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Disease-Manangement': RouteRecordInfo<
      '/posts/Disease-Manangement',
      '/posts/Disease-Manangement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Distributing-Candies': RouteRecordInfo<
      '/posts/Distributing-Candies',
      '/posts/Distributing-Candies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/example': RouteRecordInfo<
      '/posts/example',
      '/posts/example',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/exgcd': RouteRecordInfo<
      '/posts/exgcd',
      '/posts/exgcd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FPGA_start': RouteRecordInfo<
      '/posts/FPGA_start',
      '/posts/FPGA_start',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Gaussian-Elimination': RouteRecordInfo<
      '/posts/Gaussian-Elimination',
      '/posts/Gaussian-Elimination',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/github': RouteRecordInfo<
      '/posts/github',
      '/posts/github',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Horner-Algorithm': RouteRecordInfo<
      '/posts/Horner-Algorithm',
      '/posts/Horner-Algorithm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Huffman-Zip': RouteRecordInfo<
      '/posts/Huffman-Zip',
      '/posts/Huffman-Zip',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Keep-Eating-Lemons': RouteRecordInfo<
      '/posts/Keep-Eating-Lemons',
      '/posts/Keep-Eating-Lemons',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Knapsack-Problem': RouteRecordInfo<
      '/posts/Knapsack-Problem',
      '/posts/Knapsack-Problem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Lab-Report-2': RouteRecordInfo<
      '/posts/Lab-Report-2',
      '/posts/Lab-Report-2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LaTeX-Font-Syntax-Summary': RouteRecordInfo<
      '/posts/LaTeX-Font-Syntax-Summary',
      '/posts/LaTeX-Font-Syntax-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/LuoTianyi_Concert2024': RouteRecordInfo<
      '/posts/LuoTianyi_Concert2024',
      '/posts/LuoTianyi_Concert2024',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Maximal-Rectangle-Area': RouteRecordInfo<
      '/posts/Maximal-Rectangle-Area',
      '/posts/Maximal-Rectangle-Area',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/MemoryOfSnow': RouteRecordInfo<
      '/posts/MemoryOfSnow',
      '/posts/MemoryOfSnow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OItravel': RouteRecordInfo<
      '/posts/OItravel',
      '/posts/OItravel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Personal-Bio-High-School-Version': RouteRecordInfo<
      '/posts/Personal-Bio-High-School-Version',
      '/posts/Personal-Bio-High-School-Version',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Pollard-Rho-Algorithm': RouteRecordInfo<
      '/posts/Pollard-Rho-Algorithm',
      '/posts/Pollard-Rho-Algorithm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/RQYsCodeStyle4OI': RouteRecordInfo<
      '/posts/RQYsCodeStyle4OI',
      '/posts/RQYsCodeStyle4OI',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Segment-Tree-and-Fenwick-Tree': RouteRecordInfo<
      '/posts/Segment-Tree-and-Fenwick-Tree',
      '/posts/Segment-Tree-and-Fenwick-Tree',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Simulation-Contest-Summary': RouteRecordInfo<
      '/posts/Simulation-Contest-Summary',
      '/posts/Simulation-Contest-Summary',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solution-Link': RouteRecordInfo<
      '/posts/Solution-Link',
      '/posts/Solution-Link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solution-P1011': RouteRecordInfo<
      '/posts/Solution-P1011',
      '/posts/Solution-P1011',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solution-P2024': RouteRecordInfo<
      '/posts/Solution-P2024',
      '/posts/Solution-P2024',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solution-P2661': RouteRecordInfo<
      '/posts/Solution-P2661',
      '/posts/Solution-P2661',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solution-P4155': RouteRecordInfo<
      '/posts/Solution-P4155',
      '/posts/Solution-P4155',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Solving-Equations': RouteRecordInfo<
      '/posts/Solving-Equations',
      '/posts/Solving-Equations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ST-Table': RouteRecordInfo<
      '/posts/ST-Table',
      '/posts/ST-Table',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Template-Practice': RouteRecordInfo<
      '/posts/Template-Practice',
      '/posts/Template-Practice',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Total-Probability-Theorem': RouteRecordInfo<
      '/posts/Total-Probability-Theorem',
      '/posts/Total-Probability-Theorem',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Tree-Traversal-DFS-and-BFS': RouteRecordInfo<
      '/posts/Tree-Traversal-DFS-and-BFS',
      '/posts/Tree-Traversal-DFS-and-BFS',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/website': RouteRecordInfo<
      '/posts/website',
      '/posts/website',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Xuan-Fly-Loves-Math': RouteRecordInfo<
      '/posts/Xuan-Fly-Loves-Math',
      '/posts/Xuan-Fly-Loves-Math',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/YourLifeInApril': RouteRecordInfo<
      '/posts/YourLifeInApril',
      '/posts/YourLifeInApril',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.11_@babel+parse_6acf1de78d9d344bbb528dc1f80d33a2/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/anime-grid/index.md': {
      routes:
        | '/anime-grid/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/anxiary/index.md': {
      routes:
        | '/anxiary/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_2260f480eb1f3087584c8cca15ced94b/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/paper/Eyeriss.md': {
      routes:
        | '/paper/Eyeriss'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/paper/StringingSpills.md': {
      routes:
        | '/paper/StringingSpills'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.11_ma_2260f480eb1f3087584c8cca15ced94b/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/11.11-Simulation-Contest-Summary.md': {
      routes:
        | '/posts/11.11-Simulation-Contest-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/11.12-Simulation-Contest-Summary.md': {
      routes:
        | '/posts/11.12-Simulation-Contest-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/11.13-Simulation-Contest-Summary.md': {
      routes:
        | '/posts/11.13-Simulation-Contest-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/11.9-Simulation-Contest-Summary.md': {
      routes:
        | '/posts/11.9-Simulation-Contest-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/aboutme.md': {
      routes:
        | '/posts/aboutme'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/anime2023.md': {
      routes:
        | '/posts/anime2023'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Another-Request.md': {
      routes:
        | '/posts/Another-Request'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/apple-tree-2.md': {
      routes:
        | '/posts/apple-tree-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CCF-Arch-Fault-Injection-Survey-2021-2025.md': {
      routes:
        | '/posts/CCF-Arch-Fault-Injection-Survey-2021-2025'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/College-Literature.md': {
      routes:
        | '/posts/College-Literature'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Common-Mistakes.md': {
      routes:
        | '/posts/Common-Mistakes'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_1.md': {
      routes:
        | '/posts/CourseOfDCS_1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_10.md': {
      routes:
        | '/posts/CourseOfDCS_10'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_2.md': {
      routes:
        | '/posts/CourseOfDCS_2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_3.md': {
      routes:
        | '/posts/CourseOfDCS_3'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_4.md': {
      routes:
        | '/posts/CourseOfDCS_4'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_5.md': {
      routes:
        | '/posts/CourseOfDCS_5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_6.md': {
      routes:
        | '/posts/CourseOfDCS_6'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_7.md': {
      routes:
        | '/posts/CourseOfDCS_7'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_8.md': {
      routes:
        | '/posts/CourseOfDCS_8'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_9.md': {
      routes:
        | '/posts/CourseOfDCS_9'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfDCS_highlight.md': {
      routes:
        | '/posts/CourseOfDCS_highlight'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfFaultTorrence.md': {
      routes:
        | '/posts/CourseOfFaultTorrence'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CourseOfISP.md': {
      routes:
        | '/posts/CourseOfISP'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/DiaryOfKeyan240827.md': {
      routes:
        | '/posts/DiaryOfKeyan240827'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Disease-Manangement.md': {
      routes:
        | '/posts/Disease-Manangement'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Distributing-Candies.md': {
      routes:
        | '/posts/Distributing-Candies'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/example.md': {
      routes:
        | '/posts/example'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/exgcd.md': {
      routes:
        | '/posts/exgcd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/FPGA_start.md': {
      routes:
        | '/posts/FPGA_start'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Gaussian-Elimination.md': {
      routes:
        | '/posts/Gaussian-Elimination'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/github.md': {
      routes:
        | '/posts/github'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Horner-Algorithm.md': {
      routes:
        | '/posts/Horner-Algorithm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Huffman-Zip.md': {
      routes:
        | '/posts/Huffman-Zip'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Keep-Eating-Lemons.md': {
      routes:
        | '/posts/Keep-Eating-Lemons'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Knapsack-Problem.md': {
      routes:
        | '/posts/Knapsack-Problem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Lab-Report-2.md': {
      routes:
        | '/posts/Lab-Report-2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/LaTeX-Font-Syntax-Summary.md': {
      routes:
        | '/posts/LaTeX-Font-Syntax-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/LuoTianyi_Concert2024.md': {
      routes:
        | '/posts/LuoTianyi_Concert2024'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Maximal-Rectangle-Area.md': {
      routes:
        | '/posts/Maximal-Rectangle-Area'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/MemoryOfSnow.md': {
      routes:
        | '/posts/MemoryOfSnow'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/OItravel.md': {
      routes:
        | '/posts/OItravel'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Personal-Bio-High-School-Version.md': {
      routes:
        | '/posts/Personal-Bio-High-School-Version'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Pollard-Rho-Algorithm.md': {
      routes:
        | '/posts/Pollard-Rho-Algorithm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/RQYsCodeStyle4OI.md': {
      routes:
        | '/posts/RQYsCodeStyle4OI'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Segment-Tree-and-Fenwick-Tree.md': {
      routes:
        | '/posts/Segment-Tree-and-Fenwick-Tree'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Simulation-Contest-Summary.md': {
      routes:
        | '/posts/Simulation-Contest-Summary'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solution-Link.md': {
      routes:
        | '/posts/Solution-Link'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solution-P1011.md': {
      routes:
        | '/posts/Solution-P1011'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solution-P2024.md': {
      routes:
        | '/posts/Solution-P2024'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solution-P2661.md': {
      routes:
        | '/posts/Solution-P2661'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solution-P4155.md': {
      routes:
        | '/posts/Solution-P4155'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Solving-Equations.md': {
      routes:
        | '/posts/Solving-Equations'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ST-Table.md': {
      routes:
        | '/posts/ST-Table'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Template-Practice.md': {
      routes:
        | '/posts/Template-Practice'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Total-Probability-Theorem.md': {
      routes:
        | '/posts/Total-Probability-Theorem'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Tree-Traversal-DFS-and-BFS.md': {
      routes:
        | '/posts/Tree-Traversal-DFS-and-BFS'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/website.md': {
      routes:
        | '/posts/website'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Xuan-Fly-Loves-Math.md': {
      routes:
        | '/posts/Xuan-Fly-Loves-Math'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/YourLifeInApril.md': {
      routes:
        | '/posts/YourLifeInApril'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
