/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/anime-grid/': RouteRecordInfo<'/anime-grid/', '/anime-grid', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/11.11-Simulation-Contest-Summary': RouteRecordInfo<'/posts/11.11-Simulation-Contest-Summary', '/posts/11/11-Simulation-Contest-Summary', Record<never, never>, Record<never, never>>,
    '/posts/11.12-Simulation-Contest-Summary': RouteRecordInfo<'/posts/11.12-Simulation-Contest-Summary', '/posts/11/12-Simulation-Contest-Summary', Record<never, never>, Record<never, never>>,
    '/posts/11.13-Simulation-Contest-Summary': RouteRecordInfo<'/posts/11.13-Simulation-Contest-Summary', '/posts/11/13-Simulation-Contest-Summary', Record<never, never>, Record<never, never>>,
    '/posts/11.9-Simulation-Contest-Summary': RouteRecordInfo<'/posts/11.9-Simulation-Contest-Summary', '/posts/11/9-Simulation-Contest-Summary', Record<never, never>, Record<never, never>>,
    '/posts/aboutme': RouteRecordInfo<'/posts/aboutme', '/posts/aboutme', Record<never, never>, Record<never, never>>,
    '/posts/anime2023': RouteRecordInfo<'/posts/anime2023', '/posts/anime2023', Record<never, never>, Record<never, never>>,
    '/posts/Another-Request': RouteRecordInfo<'/posts/Another-Request', '/posts/Another-Request', Record<never, never>, Record<never, never>>,
    '/posts/apple-tree-2': RouteRecordInfo<'/posts/apple-tree-2', '/posts/apple-tree-2', Record<never, never>, Record<never, never>>,
    '/posts/College-Literature': RouteRecordInfo<'/posts/College-Literature', '/posts/College-Literature', Record<never, never>, Record<never, never>>,
    '/posts/Common-Mistakes': RouteRecordInfo<'/posts/Common-Mistakes', '/posts/Common-Mistakes', Record<never, never>, Record<never, never>>,
    '/posts/Disease-Manangement': RouteRecordInfo<'/posts/Disease-Manangement', '/posts/Disease-Manangement', Record<never, never>, Record<never, never>>,
    '/posts/Distributing-Candies': RouteRecordInfo<'/posts/Distributing-Candies', '/posts/Distributing-Candies', Record<never, never>, Record<never, never>>,
    '/posts/example': RouteRecordInfo<'/posts/example', '/posts/example', Record<never, never>, Record<never, never>>,
    '/posts/exgcd': RouteRecordInfo<'/posts/exgcd', '/posts/exgcd', Record<never, never>, Record<never, never>>,
    '/posts/Gaussian-Elimination': RouteRecordInfo<'/posts/Gaussian-Elimination', '/posts/Gaussian-Elimination', Record<never, never>, Record<never, never>>,
    '/posts/github': RouteRecordInfo<'/posts/github', '/posts/github', Record<never, never>, Record<never, never>>,
    '/posts/Horner-Algorithm': RouteRecordInfo<'/posts/Horner-Algorithm', '/posts/Horner-Algorithm', Record<never, never>, Record<never, never>>,
    '/posts/Huffman-Zip': RouteRecordInfo<'/posts/Huffman-Zip', '/posts/Huffman-Zip', Record<never, never>, Record<never, never>>,
    '/posts/Keep-Eating-Lemons': RouteRecordInfo<'/posts/Keep-Eating-Lemons', '/posts/Keep-Eating-Lemons', Record<never, never>, Record<never, never>>,
    '/posts/Knapsack-Problem': RouteRecordInfo<'/posts/Knapsack-Problem', '/posts/Knapsack-Problem', Record<never, never>, Record<never, never>>,
    '/posts/Lab-Report-2': RouteRecordInfo<'/posts/Lab-Report-2', '/posts/Lab-Report-2', Record<never, never>, Record<never, never>>,
    '/posts/LaTeX-Font-Syntax-Summary': RouteRecordInfo<'/posts/LaTeX-Font-Syntax-Summary', '/posts/LaTeX-Font-Syntax-Summary', Record<never, never>, Record<never, never>>,
    '/posts/Maximal-Rectangle-Area': RouteRecordInfo<'/posts/Maximal-Rectangle-Area', '/posts/Maximal-Rectangle-Area', Record<never, never>, Record<never, never>>,
    '/posts/OItravel': RouteRecordInfo<'/posts/OItravel', '/posts/OItravel', Record<never, never>, Record<never, never>>,
    '/posts/Personal-Bio-High-School-Version': RouteRecordInfo<'/posts/Personal-Bio-High-School-Version', '/posts/Personal-Bio-High-School-Version', Record<never, never>, Record<never, never>>,
    '/posts/Pollard-Rho-Algorithm': RouteRecordInfo<'/posts/Pollard-Rho-Algorithm', '/posts/Pollard-Rho-Algorithm', Record<never, never>, Record<never, never>>,
    '/posts/RQYsCodeStyle4OI': RouteRecordInfo<'/posts/RQYsCodeStyle4OI', '/posts/RQYsCodeStyle4OI', Record<never, never>, Record<never, never>>,
    '/posts/Segment-Tree-and-Fenwick-Tree': RouteRecordInfo<'/posts/Segment-Tree-and-Fenwick-Tree', '/posts/Segment-Tree-and-Fenwick-Tree', Record<never, never>, Record<never, never>>,
    '/posts/Simulation-Contest-Summary': RouteRecordInfo<'/posts/Simulation-Contest-Summary', '/posts/Simulation-Contest-Summary', Record<never, never>, Record<never, never>>,
    '/posts/Solution-Link': RouteRecordInfo<'/posts/Solution-Link', '/posts/Solution-Link', Record<never, never>, Record<never, never>>,
    '/posts/Solution-P1011': RouteRecordInfo<'/posts/Solution-P1011', '/posts/Solution-P1011', Record<never, never>, Record<never, never>>,
    '/posts/Solution-P2024': RouteRecordInfo<'/posts/Solution-P2024', '/posts/Solution-P2024', Record<never, never>, Record<never, never>>,
    '/posts/Solution-P2661': RouteRecordInfo<'/posts/Solution-P2661', '/posts/Solution-P2661', Record<never, never>, Record<never, never>>,
    '/posts/Solution-P4155': RouteRecordInfo<'/posts/Solution-P4155', '/posts/Solution-P4155', Record<never, never>, Record<never, never>>,
    '/posts/Solving-Equations': RouteRecordInfo<'/posts/Solving-Equations', '/posts/Solving-Equations', Record<never, never>, Record<never, never>>,
    '/posts/ST-Table': RouteRecordInfo<'/posts/ST-Table', '/posts/ST-Table', Record<never, never>, Record<never, never>>,
    '/posts/Template-Practice': RouteRecordInfo<'/posts/Template-Practice', '/posts/Template-Practice', Record<never, never>, Record<never, never>>,
    '/posts/Total-Probability-Theorem': RouteRecordInfo<'/posts/Total-Probability-Theorem', '/posts/Total-Probability-Theorem', Record<never, never>, Record<never, never>>,
    '/posts/Tree-Traversal-DFS-and-BFS': RouteRecordInfo<'/posts/Tree-Traversal-DFS-and-BFS', '/posts/Tree-Traversal-DFS-and-BFS', Record<never, never>, Record<never, never>>,
    '/posts/website': RouteRecordInfo<'/posts/website', '/posts/website', Record<never, never>, Record<never, never>>,
    '/posts/Xuan-Fly-Loves-Math': RouteRecordInfo<'/posts/Xuan-Fly-Loves-Math', '/posts/Xuan-Fly-Loves-Math', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
